### ISSUE TITLE
relative rotation not maintained on constraint

### ISSUE THREAD

**Issue by pixelmaid** [mitmedialab/para#62]
when constraining on rotation, after the constraint is created, the relative object will match the rotation of the reference rather than maintaining a relative constraint based on its current rotation.

**Comment by TheSumitGogia** [comment]
this is actually more superficial; the correct constraint is created, it's just that the view doesn't update until other actions (such as selection or tool switching) are performed - adding a paper view update line to the constraint creation section fixes

**Comment by pixelmaid** [comment]
The constraint does update when the paper view update is called through another action (like selecting a different tool), however when this occurs, the rotation of the relative object is updated to match the reference. The screenshots show what I'm talking about. The rectangle should be constrained to the rotation of the hexagon, but with an offset that maintains its original rotation of zero initially. Instead it is rotated to the same angle as the hexagon after the constraint is created. 

constraint created, but before canvas update
![image](https://cloud.githubusercontent.com/assets/295733/7971720/b646f206-09fb-11e5-93bf-36c585f04751.png)

after canvas update
![image](https://cloud.githubusercontent.com/assets/295733/7971699/9c5b8884-09fb-11e5-8803-a169c1654b34.png)

**Comment by TheSumitGogia** [comment]
I see what you're saying now. I'll review the constraint function code - I'm going to need to change it to accommodate the curve editor anyways.

**Comment by pixelmaid** [comment]
Issue was caused because constraint expression offset was generated by referencing the rotation property on the paper.js proxy object, which is not persistent. Constraint expression offsets are now created by referencing the rotation delta on the instance itself. The same has been implemented for scaling. Eventually we should remove the proxy object altogether..
